#!/usr/bin/env bash
# A script to install nginx on your web-01
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
