#!/usr/bin/env bash
# A script to configure Nginx so that its HTTP response
# Contains a custom header (on web-01 and web-02).

apt-get  update ; apt-get -y install nginx
string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
sudo service nginx restart
