#!/usr/bin/env bash
# A script to configure Nginx so that its HTTP response
# Contains a custom header (on web-01 and web-02).

# Install nginx web server
sudo apt update
sudo apt install -y nginx

# Setup custom http response header
sudo sed -i "s/listen \[::\]:80 default_server;/&\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default

# Restart nginx server
sudo service nginx restart
