#!/usr/bin/env bash
# This script displays
# Infinity and beyond indefinitely
# with a sleep 2 in between each iteration

trap "echo 'I am invincible!!!'" 15

while true
do
    echo "To infinity and beyond"
    sleep 2
done
